Выполнение задания 18 спринта
skukharev/TravelPlanner pull request #1
Opened 2024-10-18 12:54 UTC by skukharev

Доброго дня!

Прошу провести ревью моего домашнего задания в спринте 18.

С уважением,
Сергей Кухарев

2024-10-18 18:47 UTC, protos17 requested changes

2024-10-18 18:47 UTC, protos17 commented on TravelPlanner/TravelPlannerApp.swift
> +                    print("(5) ============ https://api.rasp.yandex.net/v3.0/nearest_stations/ - OK ==============")
При копипасте тут должно выводить nearest_settlement, а у тебя nearest_stations

2024-10-18 18:47 UTC, protos17 commented on TravelPlanner/TravelPlannerApp.swift
> +        /// (7) Проверка работоспособности ручки https://yandex.ru/dev/rasp/doc/ru/reference/stations_list
Тут можно было бы просто все методы указать как async и вызвать их в одном Task

2024-10-18 18:47 UTC, protos17 commented on TravelPlanner/Services/CarrierService.swift
> +    func getCarrier(code: String) async throws -> Result<CarrierResponse, Error>
Рекомендую здесь и везде по проекту пройти и убрать `Result`, оставив только тело самого ответа (CarrierResponse) потому что метод указан как `throws` и ошибку он выдаст сам

2024-10-18 18:47 UTC, protos17 commented on TravelPlanner/Services/CarrierService.swift
> +                apikey: apikey,
Сейчас ты передаешь apikey напрямую в запрос. Но сервисы не всегда принимают ключи авторизации в строке запроса. 
Часто авторизация проходит через добавление заголовков в запрос. Кстати, API сервисов «Яндекс Расписаний» тоже позволяет это делать.
[Пример прикрепления нужного хэдэра к запросу от создателей генератора кода](<https://github.com/apple/swift-openapi-generator/tree/main/Examples/auth-client-middleware-example>).

2024-10-18 18:47 UTC, protos17 commented on TravelPlanner/Services/OpenApi/openapi.yaml
> +            application/json:
Чтобы не выдавало ошибку, тут надо указать: 

    text/html:

2024-10-18 18:47 UTC, protos17 commented on TravelPlanner/TravelPlannerApp.swift
> +        /// (1) Проверка работоспособности ручки https://api.rasp.yandex.net/v3.0/search/
Можешь для таких проверок создать тест с помощью XCTest и будет вообще идеально. Просто добавить проверку, что запрос не выдает ошибку

2024-10-19 13:18 UTC, skukharev commented on TravelPlanner/Services/CarrierService.swift
> +                apikey: apikey,
Спасибо за пример - действительно, редко когда авторизация производится через get-параметр

2024-10-19 13:19 UTC, skukharev commented on TravelPlanner/Services/OpenApi/openapi.yaml
> +            application/json:
Спасибо за ссылку с решением. Задавал вопрос в Пачке, но так никто и не ответил, как решается эта проблема с несоответствием back-end описанию. Считаю это ошибкой разработчиков back-end - написал на сайте обратную связь, но вряд ли исправят...

2024-10-19 17:25 UTC, protos17 approved these changes

2024-10-19 17:25 UTC, protos17 commented on TravelPlanner/Services/StationsListService.swift
> +        return try self.decode(T.self, from: data)
Рекомендую расширения выносить в отдельный файл

2024-10-19 17:25 UTC, protos17 commented on TravelPlanner/TravelPlannerApp.swift
>      }
Все методы рекомендую заменить без completion и без Result, потому что использование async/await избавляет нас от этого и код становится более лаконичным. Чтобы потом в тестах его вызвать, нужно просто тестовый метод указать как `async`.

    func schedulesBetweenStations(fromStation: String, toStation: String) async throws -> SchedulesBetweenStationsResponse {
        let client = Client(
            serverURL: try Servers.server1(),
            transport: URLSessionTransport(),
            middlewares: [AuthenticationMiddleware(authorizationHeaderFieldValue: GlobalConstants.yandexSchedulesApi)]
        )

        let service = SchedulesBetweenStationService(client: client)
        return try await service.getSchedulesBetweenStations(fromStation: fromStation, toStation: toStation)
    }

2024-10-19 17:25 UTC, protos17 commented on TravelPlannerTests/TravelPlannerTests.swift
> +    }
Чтобы протестировать асинхронные функции, достаточно просто метод указать как async. Рекомендую тесты заменить на код такого плана:

    func testSchedulesBetweenStations() async throws {
        let expectation = expectation(description: "testSchedulesBetweenStations")
        do {
            let result = try await travelPlanner.schedulesBetweenStations(fromStation: "c146", toStation: "c213")
            XCTAssertNotNil(result)
            expectation.fulfill()
        } catch {
            XCTFail(error.localizedDescription)
        }
        await fulfillment(of: [expectation], timeout: 10)
    }

2024-10-20 06:09 UTC, skukharev commented
Данил, добрый день!

Спасибо за советы - теперь я понял преимущества async/await. Код получается лаконичнее и понятнее. Круто!
Также спасибо за подсказку по решению проблемы с неожидаемым типом возвращаемого ответа от сервера в stations_list

2024-10-20 06:09 UTC, merged